name: Setup mise
description: miseをインストールし、mise.tomlで指定されたツール群をセットアップする

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        version: 2026.3.10
        install: true
        install_args: ""
        cache: true
        experimental: true
        log_level: debug
        working_directory: .
        reshim: false
